//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab24.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string itemname { get; set; }
        public string itemdescription { get; set; }
        public string itemquantity { get; set; }
        public decimal itemprice { get; set; }
    }
}
